// vue-app/src/components/Counter.vue
<template>
    <div>
        <h1>Contador</h1>
        <div class="count-container">{{ count }}</div>
        <div>
            <button @click="decrement">Decrementar</button>
            <button @click="reset">Resetear</button>
            <button @click="increment">Incrementar</button>
        </div>
    </div>
</template>

<script setup>
import { ref } from 'vue';

const count = ref(0);

const increment = () => {
  count.value++;
};

const decrement = () => {
  count.value--;
};

const reset = () => {
  count.value = 0;
};
</script>

// react-app/src/components/Counter.jsx
import useCounter from "../hooks/useCounter";
import Button from "./Button";

const Counter = () => {

    const { increment, decrement, reset, count } = useCounter() ;

    return (
        <main>
            <h1>Contador</h1>
            <div className='count-container'>{count}</div>
            <div>
                <Button onClick={decrement} text="Decrementar" /> 
                <Button onClick={reset} text="Resetear" />
                <Button onClick={increment} text="Incrementar" />
            </div>
        </main>
    );
};

export default Counter;
